version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/remotelocal
permissions:
   - object: /home/ec2-user/
     pattern: "**"
     mode: 775
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
#  BeforeInstall:
#    - location: scripts/clean.sh
#      timeout: 300
#      runas: root
#  AfterInstall:
#    - location: scripts/bundle_install.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
